package parser

var Fluids = map[string]string{
	"grc.grapewine0":  "Grape Wine\\n(Young)",
	"grc.grapewine1":  "Grape Wine\\n(Fermented)",
	"grc.grapewine2":  "Grape Wine\\n(Potent)",
	"grc.grapewine3":  "Grape Wine\\n(Extended)",
	"grc.grapewine4":  "Ambrosia\\n(Hyper-Extended)",
	"grc.grapewine5":  "Port Wine\\n(Fortified)",
	"grc.grapewine6":  "Grape Wine\\n(Intoxicated)",
	"grc.grapewine7":  "Grape Wine\\n(Poisoned)",
	"grc.applecider0": "Apple Cider\\n(Young)",
	"grc.applecider1": "Apple Cider\\n(Fermented)",
	"grc.applecider2": "Apple Cider\\n(Potent)",
	"grc.applecider3": "Apple Cider\\n(Extended)",
	"grc.applecider4": "Silken Nectar\\n(Magical)",
	"grc.applecider5": "Apple Cider\\n(Intoxicated)",
	"grc.applecider6": "Apple Cider\\n(Poisoned)",
	"grc.hopale0":     "Ale\\n(Young, Hopped)",
	"grc.hopale1":     "Ale\\n(Fermented)",
	"grc.hopale2":     "Ale\\n(Potent)",
	"grc.hopale3":     "Ale\\n(Extended)",
	"grc.hopale4":     "Ale\\n(Young, No Hops)",
	"grc.hopale5":     "Ale\\n(Hyper-Extended)",
	"grc.hopale6":     "Ale\\n(Chilled)",
	"grc.hopale7":     "Ale\\n(Intoxicated)",
	"grc.hopale8":     "Ale\\n(Poisoned)",
	"grc.lager0":      "Lager\\n(Young, Chilled)",
	"grc.lager1":      "Lager\\n(Fermented)",
	"grc.lager2":      "Lager\\n(Potent)",
	"grc.lager3":      "Lager\\n(Extended)",
	"grc.lager4":      "Lager\\n(Hyper-Extended)",
	"grc.lager5":      "Lager\\n(Intoxicated)",
	"grc.lager6":      "Lager\\n(Poisoned)",
	"grc.ricesake0":   "Sake\\n(Young)",
	"grc.ricesake1":   "Sake\\n(Fermented)",
	"grc.ricesake2":   "Sake\\n(Potent)",
	"grc.ricesake3":   "Sake\\n(Extended)",
	"grc.ricesake4":   "Divine Sake\\n(Hyper-Extended)",
	"grc.ricesake5":   "Sake\\n(Intoxicated)",
	"grc.ricesake6":   "Sake\\n(Poisoned)",
	"grc.honeymead0":  "Mead\\n(Young)",
	"grc.honeymead1":  "Mead\\n(Fermented)",
	"grc.honeymead2":  "Mead\\n(Potent)",
	"grc.honeymead3":  "Mead\\n(Extended)",
	"grc.honeymead4":  "Mead\\n(Hyper-Extended)",
	"grc.honeymead5":  "Mead\\n(Intoxicated)",
	"grc.honeymead6":  "Mead\\n(Poisoned)",
}
var Items = map[string]string{
	"minecraft:dye:15":                "Bone Meal",
	"minecraft:apple:0":               "Apple",
	"minecraft:nether_wart:0":         "Nether Wart",
	"minecraft:wheat:0":               "Wheat",
	"minecraft:redstone:0":            "Redstone Dust",
	"minecraft:glowstone_dust:0":      "Glowstone Dust",
	"Growthcraft|Grapes:grc.grapes:0": "Grapes",
	"Growthcraft|Rice:grc.rice:0":     "Paddy Rice",
	"Growthcraft|Hops:grc.hops:0":     "Common Hops",
	"Growthcraft|Cellar:grc.yeast:0":  "Brewers Yeast",
	"Growthcraft|Cellar:grc.yeast:1":  "Lager Yeast",
	"Growthcraft|Cellar:grc.yeast:2":  "Bayanus Yeast",
	"Growthcraft|Cellar:grc.yeast:3":  "Ethereal Yeast",
	"Growthcraft|Cellar:grc.yeast:4":  "Origin Yeast",
}
